"""empty message

Revision ID: 7effbb323608
Revises: 2cd33f5424a8
Create Date: 2023-07-30 09:51:01.223002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7effbb323608'
down_revision = '2cd33f5424a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
